### ISSUE TITLE
Can I use bun:sqlite?

### ISSUE THREAD

**Issue by gandli** [gustavocadev/nextjs-drizzle-orm-sqlite#2]
db/index.ts

```
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { Database } from "bun:sqlite";
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from './schema';
import process from 'node:process'

// Load the environment variables from the .env file
process.loadEnvFile()

const sqlite = new Database(process.env.DB_URL!);
export const db: BetterSQLite3Database<typeof schema> = drizzle(sqlite, {
  // to use query builders like findMany()
  schema,
});

// this is important to bring the schema into the database, otherwise the tables won't be created
migrate(db, { migrationsFolder: 'drizzle' });
```

**Comment by gustavocadev** [comment]
> db/index.ts
> 
> ```
> import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
> import { Database } from "bun:sqlite";
> import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
> import * as schema from './schema';
> import process from 'node:process'
> 
> // Load the environment variables from the .env file
> process.loadEnvFile()
> 
> const sqlite = new Database(process.env.DB_URL!);
> export const db: BetterSQLite3Database<typeof schema> = drizzle(sqlite, {
>   // to use query builders like findMany()
>   schema,
> });
> 
> // this is important to bring the schema into the database, otherwise the tables won't be created
> migrate(db, { migrationsFolder: 'drizzle' });
> ```

uhmm Yes, you could as far as know, follow the drizzle docs for bun sqlite https://orm.drizzle.team/docs/get-started-sqlite#bun-sqlite
